### ISSUE TITLE
waybackpack: error: unrecognized arguments: --start 1800

### ISSUE THREAD

**Issue by cannyboy** [bevacqua/shots#15]
After installing on Mac 10.11 (node v6.1.0, Python 2.7.11, ZSH) with 

```
pip install waybackpack
npm i -g shots -S
```

I tried to create a gif and got the following error

```
shots amazon.com
{ Error: Command failed: waybackpack amazon.com -d /var/folders/rv/y5gqb7k93ts54r9wk10d6dnr0000gp/T/tmp-15239AuADIPW91Hja/pages --start 1800
usage: waybackpack [-h] (-d DIR | --list) [--raw] [--root ROOT]
                   [--from-date FROM_DATE] [--to-date TO_DATE]
                   [--user-agent USER_AGENT] [--follow-redirects]
                   [--uniques-only] [--collapse COLLAPSE] [--quiet]
                   url
waybackpack: error: unrecognized arguments: --start 1800

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'waybackpack amazon.com -d /var/folders/rv/y5gqb7k93ts54r9wk10d6dnr0000gp/T/tmp-15239AuADIPW91Hj
```

**Comment by cannyboy** [comment]
I uninstalled waybackpack, and reinstalled with previous version:

```
pip uninstall waybackpack
pip install waybackpack==0.1.1
```

... and it appears to be running now.

**Comment by StevenACoffman** [comment]
The new parameter is `--to-date` instead of `--start` which is easy to change in the shots source code, but with that change it still appears that several other changes have been made to https://github.com/jsvine/waybackpack in https://github.com/jsvine/waybackpack/commit/fea889096906d03ca537f2538c8f42e99dc71326 that violate `shots` assumptions about the structure of downloaded pages:
- running shots with waybackpack==0.1.1 will put resources/shots/pages/www-amazon-com-19971210195548.html
- running shots with waybackpack==0.3.1 will put resources/shots/pages/19971210195548/www.amazon.com/index.html

**Comment by bevacqua** [comment]
Well that's super annoying.

**Comment by mathiasbynens** [comment]
Maybe update the `shots` installation instructions for now?

**Comment by bevacqua** [comment]
Pinned @ f5a0d947e3fcfba8de5a84bb2685b29a08d99354
